# Generated by Django 5.1.2 on 2024-10-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_projeto_delete_atividades_delete_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('feito', 'Feito'), ('em andamento', 'Em andamento'), ('não iniciado', 'Não iniciado')], max_length=20),
        ),
    ]
